version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: marshmallow-sqlalchemy
    versions:
    - 0.24.1
    - 0.24.2
